# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/notepad-app:latest',
      '.'
    ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notepad-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'notepad-app',
      '--image', 'gcr.io/$PROJECT_ID/notepad-app:latest',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--concurrency', '80',
      '--max-instances', '10',
      '--set-env-vars', 'DATABASE_URL=${_DATABASE_URL}',
      '--set-env-vars', 'DATABASE_USERNAME=${_DATABASE_USERNAME}',
      '--set-env-vars', 'DATABASE_PASSWORD=${_DATABASE_PASSWORD}',
      '--set-env-vars', 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}',
      '--set-env-vars', 'FROM_EMAIL=${_FROM_EMAIL}',
      '--set-env-vars', 'FIREBASE_SERVICE_ACCOUNT_KEY_B64=${_FIREBASE_SERVICE_ACCOUNT_KEY_B64}',
      '--set-env-vars', 'SHOW_SQL=false',
      '--set-env-vars', 'LOG_LEVEL=INFO'
    ]

# Configure environment variables as substitutions (set these in Cloud Build triggers)
substitutions:
  _DATABASE_URL: 'jdbc:postgresql://your-supabase-host:6543/postgres'
  _DATABASE_USERNAME: 'postgres.your_project_ref'
  _DATABASE_PASSWORD: 'your_database_password'
  _SENDGRID_API_KEY: 'SG.your_sendgrid_api_key_here'
  _FROM_EMAIL: 'your_email@domain.com'
  _FIREBASE_SERVICE_ACCOUNT_KEY_B64: 'your_base64_encoded_firebase_service_account_json'

# Specify timeout and machine type
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout (30 minutes)
timeout: '1800s'

images:
  - 'gcr.io/$PROJECT_ID/notepad-app:latest'