services:
  notepad-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
      - SHOW_SQL=${SHOW_SQL:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@notepad.com}

# Note: Environment variables are loaded from .env file
# No local database needed - using Supabase cloud database