server:
  port: ${PORT:8080}

spring:
  application:
    name: notepad-app
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notepad}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# SendGrid configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: ${FROM_EMAIL:noreply@notepad.com}

# Firebase configuration
firebase:
  service-account-key-b64: ${FIREBASE_SERVICE_ACCOUNT_KEY_B64:}

# Logging configuration
logging:
  level:
    com.leopad.notepad: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    com.sendgrid: ${LOG_LEVEL:INFO}
    com.google.firebase: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:OFF}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_LOG_LEVEL:OFF}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/notepad-app.log}
    max-size: 10MB
    max-history: 30