server:
  port: ${PORT:8080}

spring:
  application:
    name: notepad-app
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notepad}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection pool settings
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION:60000}
      
      # PostgreSQL-specific settings to prevent prepared statement issues
      data-source-properties:
        # Disable server-side prepared statements to avoid name collision issues
        prepareThreshold: 0
        # Set application name for easier identification in PostgreSQL logs
        ApplicationName: notepad-app-pool
        # Enable TCP keep alive
        tcpKeepAlive: true
        # Set socket timeout
        socketTimeout: 30
        # Set login timeout
        loginTimeout: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# SendGrid configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: ${FROM_EMAIL:noreply@notepad.com}

# Firebase configuration
firebase:
  service-account-key-b64: ${FIREBASE_SERVICE_ACCOUNT_KEY_B64:}

# CORS configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Logging configuration
logging:
  level:
    com.leopad.notepad: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    com.sendgrid: ${LOG_LEVEL:INFO}
    com.google.firebase: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:OFF}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_LOG_LEVEL:OFF}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/notepad-app.log}
    max-size: 10MB
    max-history: 30